### PR TITLE
limit the size 'round' and if token is nil, return the last good token

### PR DESCRIPTION
**Pull request by evantahler**

### CODE REVIEW

**Comment by jrichardlai** [comment]
I don't really understand this PR, will round not be negative if round is 0 >

**Comment by evantahler** [comment]
Notes here: https://www.pivotaltracker.com/story/show/90990632

**Comment by jrichardlai** [comment]
I dont think this will fix the timeout issue, it seems it will still be an infinite loop, what was the test you did to reproduce the timeout?

**Comment by evantahler** [comment]
It's in the tracker story.  I'll copy it here:

racksh:

```
>> url = 'https://www.taskrabbit.co.uk/something'
=> "https://www.taskrabbit.co.uk/something"
>> user_id = 78156
=> 78156
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/7aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/77aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/1f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/41f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/1e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/81e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/4c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/54c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/8c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/a8c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/6a8c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/c6a8c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/2c6a8c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/d2c6a8c254c6881e441f0c8977aec5fc"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
=> "https://taskrabbit.co.uk/x/"
>> Shrinker::Parser::Text.replace(url, {:user_id => user_id})
```

(timeout)

**Comment by jrichardlai** [comment]
Oh I see what is happening for the nil case:

```
[22] pry(main)> Digest::MD5.hexdigest("ewiorewoirnewiornweionrio")[-1*32..-1]
"51281a51cbfa58dc068e8c7a575eca7e"
[23] pry(main)> Digest::MD5.hexdigest("ewiorewoirnewiornweionrio")[-1*33..-1]
```

So maybe we should use the random strategy? And in the case of when its too long we should force random or raise.

**Comment by evantahler** [comment]
Up to you!  I just wanted to call out this was the error :D  I can't tell if there's any auth built into these URLs.  If there is, go random.  If there isn't, than opt for the same URL after the 32d try.

**Comment by jrichardlai** [comment]
Yeah good job catching it :+1: Also if we use random we dont need to do this round number thing, Its okay if code are long, and I prefer them being long and the same size. If needed we should just allow more characters like numbers and upercase lowercase, will fix this all. ( not sure if there case sensitivity in redis )

**Comment by evantahler** [comment]
@jrichardlai so are you going to make a change, or do you want to go with this?

**Comment by jrichardlai** [comment]
I'll take a look today

**Comment by jrichardlai** [comment]
@evantahler @bleonard 

https://github.com/taskrabbit/switchboard/pull/14

**Comment by jrichardlai** [comment]
Updated the PR to never return nil values

**Pull request closed without merging**
